services: 
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mert
      - POSTGRES_DB=incidence_database
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  
      
  airflow:
    image: apache/airflow:latest
    command: bash -c "airflow standalone"
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:mert@postgres/incidence_database
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    depends_on:
      - postgres

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    command: bash -c "sleep 30 && run.sh" 
    depends_on:
      - postgres

